<?php
$lang = [
    'ov_have_new_message' => '1 Yeni mesajınız var',
    'ov_have_new_messages' => '%m Yeni mesajınız var',
    'ov_free' => 'Uygun',
    'ov_place' => 'sırada',
    'ov_of' => 'oyuncu içinde',
    'ov_planet' => 'Gezegen',
    'ov_server_time' => 'Sever saati ',
    'ov_events' => 'Olaylar',
    'ov_diameter' => 'Çap',
    'ov_distance_unit' => 'km',
    'ov_temperature' => 'Sıcaklık',
    'ov_aprox' => ' arası.',
    'ov_temp_unit' => '&#186;C',
    'ov_to' => 'ile',
    'ov_position' => 'Pozisyon',
    'ov_points' => 'Puanlar',
    'ov_fields' => 'Alanlar',
];
